### ISSUE TITLE
Timbre shifting questions

### ISSUE THREAD

**Issue by hjzzju** [jurihock/stftPitchShift#27]
I would like to know if this code can keep pitch (f0) constant but change timbre (speaker identity), and if it can be overwritten with PyTorch

**Comment by jurihock** [comment]
If using CLI:

`... -p 1 -q <foo> -t <bar>`

If using Python API:

`pitchshifter.shiftpitch(..., 1, <foo>, <bar>)`

See also the full example in examples folder.

As implemented in #25 but not yet released.

Hence you currently need to clone the main branch...

**Comment by jurihock** [comment]
I decided to publish the v1.5 incl. the new timbre shifting feature, so it can be obtained from pip as regular.
