### ISSUE TITLE
Exception about resizing numpy arrays  when debugging (and only when debugging)

### ISSUE THREAD

**Issue by GrumpyBen** [jurihock/stftPitchShift#31]
"ValueError: cannot resize an array references or is referenced by another array in this way.  Use the resize function"

Looks like the debugger is not minding its business and keeping an extra reference

Corrected by changing next to last line of shiftpitch() in stftpitchshift.py from

`output.resize(np.shape(input))`

to

`np.resize(output,np.shape(input))`

**Comment by jurihock** [comment]
I've never used a debugger before... 😅

Sadly `numpy.resize` makes a copy and repeats input values in doubt, so I turned the `refcheck` option off instead, can't see anything dangerous.

**Comment by jurihock** [comment]
Fixed in 1.5.1 (pip)
