### ISSUE TITLE
Input and output options for devices

### ISSUE THREAD

**Issue by stupeed** [jurihock/stftPitchShift#33]
Hello there, sorry for English is not my native language, I want to custom your code that can do input and output through devices in real-time not a wav file and I didn’t have any programming or coding background ,where can I get start with🥺

**Comment by jurihock** [comment]
Hi,

this project provides just a "platform independent" and "application unspecific" algorithm implementation for STFT based pitch shifting, not more not less. If you plan to do something specific on top of it, make your own repository and good luck!

BTW, the `StftPitchShiftCore` #18 class is designed to integrate the pitch shifting in a custom real-time capable STFT pipeline coupled on platform specific audio IO. This project will not provide such specific type of STFT pipeline.

**Comment by stupeed** [comment]
Hello, I still have a question, are the timbre and pitch shifting both using the StftPitchShiftCore or the timbre shifting is using another algorithm to

**Comment by jurihock** [comment]
StftPitchShiftCore applies both timbre and pitch shift.

**Comment by stupeed** [comment]
Hi i tried to build your code, what went wrong, what can I do, please help🥺https://drive.google.com/file/d/1wCrNqPt2LB4S_L7KP2wIrWDqMdhNjHvp/view?usp=sharing

**Comment by jurihock** [comment]
Build instructions are included in the readme file. And if the GitHub Actions is able to build the workflow, then so can you.

**Comment by stupeed** [comment]
What should I do `D:\下載\stftPitchShift-main\examples>cmake -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe" -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe" -B D:\下載\stftPitchShift-main\build  D:\下載\stftPitchShift-main\cpp\StftPitchShift
CMake Error: The source directory "D:/下載/stftPitchShift-main/cpp/StftPitchShift" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.`
https://drive.google.com/file/d/1Ys3UZ1gOQroG1TwxjjMPs2ehxyRrxAs7/view?usp=sharing

**Comment by stupeed** [comment]
`D:\下載\stftPitchShift-main\examples>cmake -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe" -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe" -B D:\下載\stftPitchShift-main\build  D:\下載\stftPitchShift-main
CMake Error at CMakeLists.txt:3 (project):
  Running

   'nmake' '-?'

  failed with:

   系統找不到指定的檔案。


-- Configuring incomplete, errors occurred!`

**Comment by stupeed** [comment]
🥺

**Comment by jurihock** [comment]
As I wrote above, read the [build instructions](https://github.com/jurihock/stftPitchShift#c) carefully.

**Comment by stupeed** [comment]
I tried, how can I build on windows 10, it said it hadn't found nmake, but Visaul studio was installed
