### ISSUE TITLE
Can you provide examples for vocoder, and pitchshifting? 

### ISSUE THREAD

**Issue by gptshubham595** [jurihock/stftPitchShift#34]
Hi I wanted to use vocoder and pitchshifter function but was not getting proper output as I was confused about parameter limits to be used for factor.

Is it possible to provide example for a using vocoder function and pitchshifter parameter?

Thank you

**Comment by gptshubham595** [comment]
Thank you for that page where we can play and see output it would be great if possible can you tell how to run a single terminal command for C++ also

I know how to pass arg in python but not sure about the C++

**Comment by gptshubham595** [comment]
Vocoder vocoder(1024,256,441000);
vocoder.encode(// complex number how to get this parameter)

**Comment by jurihock** [comment]
The [StftPitchShift](https://github.com/jurihock/stftPitchShift/blob/f51d0b12bf3344ff053398a54210484e7e24dba4/cpp/StftPitchShift/StftPitchShift.cpp#L150) class is designed to process a single (e.g. large) audio file at once. If you plan to process a continuous audio stream (e.g. in 100ms steps), you have to use the [StftPitchShiftCore](https://github.com/jurihock/stftPitchShift/blob/f51d0b12bf3344ff053398a54210484e7e24dba4/cpp/StftPitchShift/StftPitchShiftCore.h#LL95C10-L95C19) class inside of **your** own STFT pipeline, implemented by **yourself**. The [STFT](https://github.com/jurihock/stftPitchShift/blob/f51d0b12bf3344ff053398a54210484e7e24dba4/cpp/StftPitchShift/STFT.h#L51) pipeline provided in this project cannot handle a continuous audio stream.

**Comment by gptshubham595** [comment]
oh! got it for proper audio output for real time streaming I should use StftPitchShiftCore.

One more thing i tried vocoder like this but i got no sound for the respective can you help me if possible, definitely i will try working on StftPitchShiftCore.

```

extern "C"
JNIEXPORT jfloatArray JNICALL
Java_com_my_exaxmpleKt_vocoderNDK(JNIEnv *env,
                                                                                    jclass clazz,
                                                                                    jfloatArray input_array, 
                                                                                    jint buffer_size, //3528 used nearest and low power of 2 as 2048
                                                                                    jint sample_rate //44100 ) { 
    /* Convert input array via FFT
     * */
    stftpitchshift::RFFT rfft;
    vector<double> audioFloatData(2048); // or std::vector<double> audioDoubleData;
    
    // Populate audioFloatData or audioDoubleData with your audio samples
    vector<std::complex<double>> dftSpectrumFloat(audioFloatData.size() / 2 + 1);


    /* Fetch input array
     * */
    float *ptr = env->GetFloatArrayElements(input_array, NULL);

    for (int i = 0; i < 2048; i++) {
        audioFloatData[i] = ptr[i];
    }

    /* Transforming via FFT
     * */
    rfft.fft(audioFloatData, dftSpectrumFloat);


    //Apply vocoder
    Vocoder<double> vocoder(2048, 256, sample_rate);
    vocoder.encode(dftSpectrumFloat);

    /* Transforming back via iFFT
     * */
    rfft.ifft(dftSpectrumFloat, audioFloatData);

    //Feeding the float into the output array
    jfloatArray result = env->NewFloatArray(1024);

    float *data;
    data = static_cast<float *>(malloc(sizeof(float) * 1024));
    for (int i = 0; i < 1024; i++) {
        data[i] = (float)audioFloatData[i];
    }

    (env)->SetFloatArrayRegion(result, 0, 1024, data);

    free(data);
    return result;
}
```

**Comment by gptshubham595** [comment]
<img width="945" alt="Screenshot 2023-05-31 at 5 53 21 PM" src="https://github.com/jurihock/stftPitchShift/assets/24877361/8368031e-e461-4606-a626-06441a530dbc">


These two show pitch and vocoder applied data can you help me debug which step i missed

**Comment by jurihock** [comment]
As I wrote, you have to implement the proper STFT pipeline on your own and call the StftPitchShiftCore inside of it, e.g. between FFT and IFFT.

**Comment by jurihock** [comment]
Further reading: [DAFX](https://www.dafx.de/DAFX_Book_Page_2nd_edition/index.html) (chapter 7 *Time-frequency processing*)
