### ISSUE TITLE
Tiny (0.01s) Gaps Between Audio Outputs from stftPitchShift.shiftpitch()

### ISSUE THREAD

**Issue by Rysertio** [jurihock/stftPitchShift#37]
I tried to write an LADSPA plugin using `stftPitchShift`. However, whenever I call `shiftpitch()`, it adds a very tiny (about 0.01s) fade in and out at the start and end of each buffer it processes. Here is the plugin [code](https://gist.github.com/Rysertio/5522522572f982c05556da7bc4d16072).

I've attempted to solve it by:
* Changing the hop rate, setting the hop rate to 1 to use SDFT instead of STFT.
* Enabling RMS normalization.

Unfortunately, these attempts did not work.

**Comment by jurihock** [comment]
As mentioned in #18, #33, #34 and finally in the readme file, your have to use the `StftPitchShiftCore` instance inside of _your own_ STFT pipeline for real-time audio signal processing. The `StftPitchShift` instance can't do this stuff.

**Comment by Rysertio** [comment]
I've tried to use the `StftPitchShiftCore` in [here.](https://github.com/Rysertio/stftPitchShift/blob/main/ladspa/pitcher.cpp)
But the gaps are still there.

**Comment by jurihock** [comment]
The [STFT](https://github.com/jurihock/stftPitchShift/blob/f51d0b12bf3344ff053398a54210484e7e24dba4/cpp/StftPitchShift/STFT.h#L51) pipeline provided in this project cannot handle a continuous audio stream. It only handles a finite audio file at once. This is exactly the reason, why you hear gaps in the continuous (endless, not finite) audio stream. Instead you have to implement **your own** STFT pipeline with required capability.

**Comment by jurihock** [comment]
Further reading: [DAFX](https://www.dafx.de/DAFX_Book_Page_2nd_edition/index.html) (chapter 7 *Time-frequency processing*)
