### ISSUE TITLE
Add optional FFTW3 support

### ISSUE THREAD

**Issue by jurihock** [jurihock/stftPitchShift#6]
Although *pocketfft* is a handy and useful lib for development, the *FFTW3* seems to be more suitable for distribution, since it's already available in Debian, VCPKG and Homebrew:

* https://packages.debian.org/fftw3
* https://vcpkg.info/port/fftw3
* https://formulae.brew.sh/formula/fftw

So add FFT abstraction layer in C++ and CMake option `-DFFTW=ON` to enable it.

**Comment by jjYBdx4IL** [comment]
though it has a very restrictive license, as do most of the other audio processing libs in vcpkg.

**Comment by jurihock** [comment]
oh ok, that's true, it has a dual license GPL or [purchased](https://tlo.mit.edu/technologies/fftw-fastest-fourier-transform-west) MIT...

**Comment by jurihock** [comment]
To eliminate external dependencies in the lib, I'll introduce an abstract interface for a FFT instance. Something like this:

```
class FFT
{
public:
  virtual ~FFT() {}
  virtual void fft(const std::vector<float>& frame, std::vector<std::complex<float>>& dft) = 0;
  virtual void ifft(const std::vector<std::complex<float>>& dft, std::vector<float>& frame) = 0;
};
```

Then the concrete FFT instance is to be provided via `std::shared_ptr<FFT>`. The frame size is known in advance...

In the second step, the *pocketfft* will be replaced by a default "public domain" implementation, e.g. if no user defined FFT instance is specified.

**Comment by jurihock** [comment]
After playing around with FFTW, I'm not happy about the results:

* FFTW manages it own data storage for input and output for both r2c and c2r, so there is an extra copy overhead compared to *pocketfft* or *RFFT* (actually it's not "faster" than *pocketfft*)
* The transformation results seem to be garbage... (maybe I'm doing something wrong)

So I'll stop at this point.

[CMakeLists.txt](https://github.com/jurihock/stftPitchShift/files/8599338/CMakeLists.txt)
[FFTW.h.txt](https://github.com/jurihock/stftPitchShift/files/8599340/FFTW.h.txt)
